language: python

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
  include:
    - os: linux
      python: 3.6
    - os: osx
      language: generic

install:
  - ./travisInstall.sh

script:
  - python -u setup.py clean
  - CFLAGS="-O0 -g" python -u setup.py build_ext --inplace
  - CFLAGS="-O0 -g" PYTHONUNBUFFERED=x make test

cache:
  directories:
    - $HOME/.cache/pip
